---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
  customize:
    cpus:   1
    memory: 1024
  driver_config:
    require_chef_omnibus: true

provisioner:
  name: chef_zero
  nodes_path: "nodes"
  data_bags_path: "data_bags"
  environments_path: "environments"
  encrypted_data_bag_secret_key_path: "test/data/secret.txt"
  client_rb:
    environment: test

platforms:
- name: ubuntu-14.04
  driver_config:
    require_chef_omnibus: "11.14.6"

suites:
  - name: template
    run_list:
      - recipe[template-cookbook::default]
